### ISSUE TITLE
[Suggestion] Crop pokemon images before converting to cow

### ISSUE THREAD

**Issue by SHA65536** [tmck-code/pokesay#24]
Hey!
I saw you are cropping the cow files a bit awkwardly since they're text files
I made this package to easily crop image files according to transparency
I think this could be useful, up to you :D
https://github.com/SHA65536/ImageShrink

**Comment by tmck-code** [comment]
Oh nice, that's so cool! Yeah I'd love to try this out in a future stream :sunglasses: :shipit:

**Comment by tmck-code** [comment]
I had a thought about another way that I could use this feature as well! Eventually I want to have a "-size" parameter that allows you to only show small/medium/large pokemon

By piggybacking this tool I'd be able to tell which images are which size, can hopefully give it a go on stream some time :slightly_smiling_face:

**Comment by tmck-code** [comment]
Cropping sprites pre-conversion is now implemented thanks to this PR: https://github.com/tmck-code/pokesay/pull/71, using imagemagick `convert` as it was easily available in the image.

This has resulted in better centering of all sprites, and increased colour saturation
