### ISSUE TITLE
pokesay stalls without any inputs

### ISSUE THREAD

**Issue by humanfactors** [tmck-code/pokesay#7]
I know it's kind of a silly edge case, but `pokesay-windows-amd64` stalls without input (I haven't tested other builds). It appears it cannot break the loop in zone below until user manually escapes the standard input (`C-z <return>`), which results in the input being shown twice.

https://github.com/tmck-code/pokesay-go/blob/487afe9a85cc78f06c791c267f4fa842331844a0/cmd/pokesay.go#L38-L49

Although this is of course meant to have an input piped, I think it would be good to handle this case. In theory, we could have a more formally input handler, but that is totally overkill. Maybe documenting this would be easier...

------------------------
See example below:

![image](https://user-images.githubusercontent.com/16096044/145524597-5a71088f-4d2a-4f2a-bfd0-cf4d97114fde.png)

**Comment by tmck-code** [comment]
I've been thinking about this a bit - whether to preserve original behaviour, or deviate because it doesn't quite make sense atm.

There might be a way to make it work by using a carriage return as the token, but this might not work. I'll benchmark all the available options together in the PR when I've chosen one :call_me_hand:

**Comment by tmck-code** [comment]
Going to make a call on this one as I've left it open for a while

I think the best solution might be to just add some documentation around this behaviour/edge-case, and explain that the program is intented to be used with piped input.

The "print twice" behaviour here is the result of how the speech bubble printing works
https://github.com/tmck-code/pokesay/blob/8e83d106ccbb2bdf9fdd940d37c666b298326b19/pokesay.go#L67-L70

1. The border is printed first
2. Then STDIN is scanned for input. In this case it's from directly typing in the terminal, and you see the letters appear as you type them
3. Then, upon terminating input, the scanned STDIN text is printed in the bubble line-by-line, followed by the pokemon

It _might_ be possible to detect if the input is typed and modify the behaviour, but in lieu of any easy technique I'll add to the documentation 🤙

**Comment by humanfactors** [comment]
Thank you this is great! Legend 🥰
